routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Auth', 'middleware' => 'web'], function() {
    Route::get('login',  'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::get('register', 'LoginController@register')->name('register');
});

Route::group(['prefix' => 'admin/users'], function() {
    Route::get('user-permission/{id}', '\DangKien\RolePer\Controllers\UserRoleController@index')->name('user-permission.index');
    Route::post('user-permission/{id}', '\DangKien\RolePer\Controllers\UserRoleController@store')->name('user-permission.store');
    Route::get('role-permission/{id}', '\DangKien\RolePer\Controllers\RolePermissionController@index')->name('roles-permission.index');
    Route::post('role-permission/{id}', '\DangKien\RolePer\Controllers\RolePermissionController@store')->name('roles-permission.store');
});

Route::resource('admin/roles', '\DangKien\RolePer\Controllers\RoleController');
Route::group(['prefix' => '', 'middleware' => 'role:superadmin'], function() {
    Route::resource('admin/permissions', '\DangKien\RolePer\Controllers\PermissionController');
    Route::resource('admin/permissions-group', '\DangKien\RolePer\Controllers\PermissionGroupController');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Backend'], function() {
    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\controllers\UploadController@upload');
    

    Route::get('users/profile', 'UserController@show')->name('users.profile');
    Route::post('users/profile', 'UserController@updateSeft')->name('users.updateProfile');

    Route::get('users/change-password', 'UserController@change')->name('users.change');
    Route::post('users/change-password', 'UserController@changePassword')->name('users.changePassword');

    Route::resource('users', 'UserController');

    Route::resource('groups', 'GroupController');

    Route::resource('drivers', 'DriverController');

    Route::resource('orders', 'OrderController');

    Route::resource('languages', 'LanguagesController', ['except'=>['destroy']]);

    Route::resource('categories', 'CategoryController', ['except'=>['destroy']]);
});

Route::group(['prefix' => 'rest/admin'], function() {
    Route::get('users', 'Backend\UserController@getList');
    Route::delete('users/{id}', 'Backend\UserController@destroy');

    Route::get('languages', 'Backend\LanguagesController@list');
    Route::delete('languages/{id}', 'Backend\LanguagesController@destroy');

    Route::get('categories', 'Backend\CategoryController@list');
    Route::delete('categories/{id}', 'Backend\CategoryController@destroy');

    Route::get('groups', 'Backend\GroupController@list');
    Route::delete('groups/{id}', 'Backend\GroupController@destroy');

    Route::get('drivers', 'Backend\DriverController@list');
    Route::delete('drivers/{id}', 'Backend\DriverController@destroy');

    Route::get('orders', 'Backend\OrderController@list');
    Route::delete('orders/{id}', 'Backend\OrderController@destroy');
});

app/Models/Language.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Language extends Model
{
    protected $table = "languages";

    public $timestamps = false;
}

app/Http/Controllers/Backend/LanguagesController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Language;
use DB;

class LanguagesController extends Controller
{
    private $languageModel;
    public function __construct(Language $languageModel) {
        $this->languageModel = $languageModel;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Backend.Contents.language.index');
    }

    public function list(Request $request) {

        $order = $request->has('order') ? $request->order : 'id';
        $order_code = $request->order_code || 'desc';
        
        $languages  = $this->languageModel::orderBy($order, $order_code)
                            ->paginate(10);
                            
        return response()->json($languages);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Backend.Contents.language.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->flash();
        $this->_validateInsert($request);

        DB::beginTransaction();
        try {

            $this->languageModel->locale       = $request->locale;
            $this->languageModel->name_display = $request->name_display;
            $this->languageModel->icon         = $request->icon;
            $this->languageModel->description  = $request->description;
            $this->languageModel->status       = $request->status;

            $this->languageModel->save();
            DB::commit();
            return redirect()->route('languages.index')->with('languages', 'success');
        } catch (Exception $e) {
            DB::rollback();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $language = $this->languageModel::findOrFail($id);
        return view('Backend.Contents.language.add', array('language' => $language));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $language = $this->languageModel::findOrFail($id);
        $request->flash();
        $this->_validateUpdate($request);

        DB::beginTransaction();
        try {

            $language->locale       = $request->locale;
            $language->name_display = $request->name_display;
            $language->icon         = $request->icon;
            $language->description  = $request->description;
            $language->status       = $request->status;

            $language->save();
            DB::commit();
            return redirect()->route('languages.index')->with('languages', 'success');
        } catch (Exception $e) {
            DB::rollback();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $language = $this->languageModel::findOrFail($id);
        DB::beginTransaction();
        try {
            $language->delete();
            DB::commit();
        } catch (Exception $e) {
            DB::rollback();
        }
    }


    public function _validateInsert($request) {
        $this->validate($request, [
            'name_display' => 'required| unique:languages',
            'locale'       => 'required| unique:languages',
            'icon'         => 'required'
        ], [
        ]);
    }

    public function _validateUpdate($request) {
        $this->validate($request, [
            'name_display' => 'required',
            'locale'       => 'required',
            'icon'         => 'required'
        ], [
        ]);
    }
}

resources/views/Backend/Contents/language/add.blade.php
@extends('Backend.Layouts.default')
@section ('title', 'ZeLike 澤樣室內設計')
@section('content')
	<div id="content-container">
		<div id="page-head">
            <div id="page-title">
                <h1 class="page-header text-overflow">{!! trans('backend.language.language') !!}</h1>
            </div>
            <ol class="breadcrumb">
				<li><a href="#"><i class="demo-pli-home"></i></a></li>
				<li><a href="#">{{ isset($language) ? trans('backend.actions.update') : trans('backend.actions.create') }}</a></li>
            </ol>
        </div>
		<div id="page-content">
		    <div class="panel-body">
		        <div class="panel">
		            <div class="panel">
			            <div class="panel-heading">
			               	<div class="panel-heading">
				                <h3 class="panel-title text-main text-bold mar-no">
				                	<i class="ti-pencil"></i> {{ isset($language) ? trans('backend.actions.update') : trans('backend.actions.create') }} 
				                </h3>
				            </div>
			            </div>
		                <div class="panel-body col-sm-offset-2">
		                	<!-- data-parsley-validate -->
		                	@if (isset($language)) 
								<form action="{{ route('languages.update', @$language->id) }}" method="POST" enctype="multipart/form-data" >
									@method ('PUT')
		                	@else
								<form action="{{ route('languages.store') }}" method="POST" enctype="multipart/form-data" >
									@method ('POST')
		                	@endif
		                		@csrf
								
    		                    <div class="row">
    		                        <div class="col-sm-10">
    		                            <div class="form-group">
    		                                <label class="control-label text-bold">{!! trans('backend.language.name') !!}
    		                                	<span class="text-danger">*</span>
    		                                </label>
    		                                <input type="text" name="name_display" class="form-control"
    		                                value="{{ @$language->name_display ? $language->name_display : @old('title') }}">
    		                                @if ($errors->has('name_display'))
    			                            	<p class="text-left text-danger">{{ $errors->first('name_display') }}</p>
    			                            @endif
    		                            </div>
    		                        </div> 
    		                        <div class="col-sm-10">
    		                            <div class="form-group">
    		                                <label class="control-label text-bold">{!! trans('backend.language.code') !!}
    		                                	<span class="text-danger">*</span>
    		                                </label>
    		                                <input type="text" name="locale" class="form-control" 
    		                                value="{{ @$language->locale ? $language->locale : @old('locale') }}">
    		                                @if ($errors->has('locale'))
    			                            	<p class="text-left text-danger">{{ $errors->first('locale') }}</p>
    			                            @endif
    		                            </div>
    		                        </div>

    		                        <div class="col-sm-10">
    		                            <div class="form-group">
    		                                <label class="control-label text-bold">{!! trans('backend.language.icon') !!}
    		                                	<span class="text-danger">*</span>
    		                                </label>
    		                                <input type="text" name="icon" class="form-control"
    		                                value="{{ @$language->icon ? $language->icon : @old('icon') }}">
    		                                @if ($errors->has('icon'))
    			                            	<p class="text-left text-danger">{{ $errors->first('icon') }}</p>
    			                            @endif
    		                            </div>
    		                        </div>

	                                <div class="col-sm-10"  style="margin-bottom: 15px;">
	                                    <div class="form-group has-feedback row">
	        	                            <label class="col-sm-3 control-label text-bold" style="padding-top: 10px;">{!! trans('backend.status.status') !!}</label>
	        	                            <div class="col-sm-7">
	        	                                <div class="radio">
	        	                                    <input id="AVAILABLE" class="magic-radio" type="radio" name="status" value="{{ App\Libs\Configs\StatusConfig::CONST_AVAILABLE }}" 
	        	                                    @if (statusAvailable(old('status')) || statusAvailable(old('status')))
														checked
	        	                                    @endif
	        	                                    checked 
	        	                                    >
	        	                                    <label for="AVAILABLE"> {!! trans('backend.status.available') !!}</label>
	        	
	        	                                    <input id="DISABLE" class="magic-radio" type="radio" name="status" value="{{ App\Libs\Configs\StatusConfig::CONST_DISABLE }}"
            	                                    @if (statusDisable(old('status')))
    													checked
            	                                    @endif>
	        	                                    <label for="DISABLE"> {!! trans('backend.status.disable') !!}</label>
	        	                                </div>
	        	                        	</div>
	                                	</div>
	                            	</div>
    		                    </div>
		                		<button type="submit" class="btn btn-primary btn-block btn-form-submit"><i class="ti-save"></i></button>
		                	</form>
		                </div>
			        </div>
		        </div>
		    </div>
		</div>
	</div>
@endsection

@section ('myJs')
	
@endsection

@section ('myCss')
	
@endsection

resources/views/Backend/Contents/language/index.blade.php
@extends('Backend.Layouts.default')
@section ('title', 'ZeLike 澤樣室內設計')
@section('content')
	<div id="content-container" ng-controller="languageCtrl">
		<div id="page-head">
            <div id="page-title">
                <h1 class="page-header text-overflow">{!! trans('backend.language.language') !!}</h1>
            </div>
            <ol class="breadcrumb">
				<li><a href="#"><i class="demo-pli-home"></i></a></li>
				<li><a href="#">{{ trans("backend.actions.list") }}</a></li>
            </ol>
        </div>
		<div id="page-content">
		    <div class="panel-body">
		        <div class="panel">
		            <div class="panel-heading">
		            </div>
		            <div class="panel-body">
		            	<div class="pad-btm form-inline">
				            <div class="row">
				                <div class="col-sm-6 table-toolbar-left">
				                   <a href="{{ route('languages.create') }}" id="demo-btn-addrow" class="btn btn-purple"><i class="demo-pli-add"></i> {!! trans('backend.actions.create') !!}</a>
				                </div>
				                <div class="col-sm-6 table-toolbar-right">
				                    <div class="form-group col-sm-12">
				                        <input id="demo-input-search2" type="text" placeholder="Tìm kiếm" class="form-control col-sm-
				                        8" autocomplete="off" ng-change="actions.filter()" ng-model="filter.freetext">
				                    </div>
				                </div>
				            </div>
				        </div>
		                <div class="table-responsive">
		                    <table class="table table-bordered table-hover table-vcenter">
		                        <thead>
		                            <tr>
		                                <th class="text-center">#</th>
		                                <th>{!! trans('backend.language.name') !!}</th>
		                                <th>{!! trans('backend.language.code') !!}</th>
		                                <th>{!! trans('backend.language.icon') !!}</th>
		                                <th>{!! trans('backend.status.status') !!}</th>
		                                <th>{!! trans('backend.language.actions') !!}</th>
		                            </tr>
		                        </thead>
		                        <tbody>
		                            <tr ng-repeat="(key, language) in data.languages">
		                                <td class="text-center"> @{{ (data.page.current_page - 1) * data.page.per_page + key + 1 }} </td>
		                                <td>@{{language.name_display}}</td>
		                                <td>@{{language.locale}}</td>
		                                <td><i class="@{{language.icon}}"></i></td>
		                                <td>
		                                	<span ng-if="(language.status == '{{ App\Libs\Configs\StatusConfig::CONST_DISABLE }}')"> {!! trans('backend.status.disable') !!}</span>

		                                	<span ng-if="(language.status == '{{ App\Libs\Configs\StatusConfig::CONST_AVAILABLE }}')"> {!! trans('backend.status.available') !!}</span>
		                                </td>
		                                <td style="width: 180px">
		                                	<a href="{{ url('admin/languages') }}/@{{ language.id }}/edit" class="btn btn-info btn-icon btn-sm" >
		                                		<i class="fa-lg ti-pencil-alt"></i> {!! trans('backend.actions.update') !!}
		                                	</a>
		                                	<button class="btn btn-danger btn-sm btn-icon" ng-click="actions.delete(language.id)">
		                                		<i class="fa-lg ti-trash"></i> {!! trans('backend.actions.delete') !!}
		                                	</button>
		                                </td>
		                            </tr>
		                        </tbody>
		                    </table>
		                    <div class="text-center"> 
			                    <div paging
			                      page="data.page.current_page"  
	    						  show-first-last="true"
			                      page-size="data.page.per_page" 
			                      total="data.page.total"
			                      paging-action="actions.changePage(page)">
			                    </div> 
		                    </div>
		                </div>
		            </div>
		        </div>
		    </div>
		</div>
	</div>
@endsection

@section ('myJs')
	<script src="{{ url('angularJs/uses/factory/services/languageService.js') }}"></script>
	<script src="{{ url('angularJs/uses/ctrls/languageCtrl.js') }}"></script>
	@if (Session::has('languages') && Session::get('languages') == 'success')
	<script>
		$.toast({
		    heading: '{!! trans("backend.confirm.success") !!}',
		    heading: '{!! trans("backend.language.success_message") !!}',
		    showHideTransition: 'fade',
		    position: 'top-right',
		    icon: 'success'
		})
	</script>
	@endif
@endsection
@section ('myCss')
@endsection