routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Auth', 'middleware' => 'web'], function() {
    Route::get('login',  'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::get('register', 'LoginController@register')->name('register');
});

Route::group(['prefix' => 'admin/users'], function() {
    Route::get('user-permission/{id}', '\DangKien\RolePer\Controllers\UserRoleController@index')->name('user-permission.index');
    Route::post('user-permission/{id}', '\DangKien\RolePer\Controllers\UserRoleController@store')->name('user-permission.store');
    Route::get('role-permission/{id}', '\DangKien\RolePer\Controllers\RolePermissionController@index')->name('roles-permission.index');
    Route::post('role-permission/{id}', '\DangKien\RolePer\Controllers\RolePermissionController@store')->name('roles-permission.store');
});

Route::resource('admin/roles', '\DangKien\RolePer\Controllers\RoleController');
Route::group(['prefix' => '', 'middleware' => 'role:superadmin'], function() {
    Route::resource('admin/permissions', '\DangKien\RolePer\Controllers\PermissionController');
    Route::resource('admin/permissions-group', '\DangKien\RolePer\Controllers\PermissionGroupController');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Backend'], function() {
    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\controllers\UploadController@upload');
    

    Route::get('users/profile', 'UserController@show')->name('users.profile');
    Route::post('users/profile', 'UserController@updateSeft')->name('users.updateProfile');

    Route::get('users/change-password', 'UserController@change')->name('users.change');
    Route::post('users/change-password', 'UserController@changePassword')->name('users.changePassword');

    Route::resource('users', 'UserController');

    Route::resource('groups', 'GroupController');

    Route::resource('drivers', 'DriverController');

    Route::resource('orders', 'OrderController');

    Route::resource('languages', 'LanguagesController', ['except'=>['destroy']]);

    Route::resource('categories', 'CategoryController', ['except'=>['destroy']]);
});

Route::group(['prefix' => 'rest/admin'], function() {
    Route::get('users', 'Backend\UserController@getList');
    Route::delete('users/{id}', 'Backend\UserController@destroy');

    Route::get('languages', 'Backend\LanguagesController@list');
    Route::delete('languages/{id}', 'Backend\LanguagesController@destroy');

    Route::get('categories', 'Backend\CategoryController@list');
    Route::delete('categories/{id}', 'Backend\CategoryController@destroy');

    Route::get('groups', 'Backend\GroupController@list');
    Route::delete('groups/{id}', 'Backend\GroupController@destroy');

    Route::get('drivers', 'Backend\DriverController@list');
    Route::delete('drivers/{id}', 'Backend\DriverController@destroy');

    Route::get('orders', 'Backend\OrderController@list');
    Route::delete('orders/{id}', 'Backend\OrderController@destroy');
});

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\CategoryTranslation;
use App\Models\Language;
use App\Libs\Configs\StatusConfig;
use DB, App, Illuminate\Validation\Rule;
use Datatables;

class CategoryController extends Controller
{
	private $languageModel, $categoryModel;
	public function __construct(Language $language, Category $category, CategoryTranslation $categoryTranslation)
	{
		$this->languageModel = $language;
		$this->categoryModel = $category;
	}

    public function list(Request $request) {
        $orderName = $request->input('orderName', 'id');
        $orderBy   = $request->input('orderBy', 'desc');

        $categories = $this->categoryModel
            ->select('categories.id', 'name', 'parent_id', 'depth', 'status')
            ->join('categories_translation as t', 't.category_id', '=', 'categories.id')
            ->where('locale', App::getLocale())
            ->orderBy('depth','asc')
            ->with('translations')
            ->get();

        return response()->json($categories);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('Backend.Contents.category.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = app('Category')->listCategory('vi');

        return view('Backend.Contents.category.add', 
                            array('categories' => $categories) );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->flash();
        $this->_validateInsert($request);
        DB::beginTransaction();
        $languages = $this->languageModel::where('status', StatusConfig::CONST_AVAILABLE)
        							  ->get(); 
 
        try {
            $this->categoryModel->parent_id = $request->parent_id;
            $this->categoryModel->status    = $request->status;
            $this->categoryModel->save();

        	foreach ($languages as $key => $language) {
				$this->categoryModel->translateOrNew($language->locale)->name             = $request->name[$language->id];
				$this->categoryModel->translateOrNew($language->locale)->description      = $request->description[$language->id];
				$this->categoryModel->translateOrNew($language->locale)->slug             = slugTitle($request->name[$language->id]);
				$this->categoryModel->translateOrNew($language->locale)->meta_title       = $request->meta_title[$language->id];
				$this->categoryModel->translateOrNew($language->locale)->meta_description = $request->meta_description[$language->id];
				$this->categoryModel->translateOrNew($language->locale)->meta_data        = $request->meta_content[$language->id];
				$this->categoryModel->save();
        	}
            $this->_updateParent($request->parent_id, $this->categoryModel->id);
        	DB::commit();
            return redirect()->route('categories.index')->with('category', 'success');
        } catch (Exception $e) {
        	DB::rollback();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categoryModel->findOrFail($id);
        $categories = app('Category')->listCategory('vi');
  
        return view('Backend.Contents.category.add', array('category' => $category, 
                                                        'categories' => $categories));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        DB::beginTransaction();
        $languages = $this->languageModel::where('status', StatusConfig::CONST_AVAILABLE)
                                            ->get(); 
        $categoryModel = $this->categoryModel->findOrFail($id);

        try {
            $categoryModel->status    = $request->status;
            $categoryModel->parent_id = $request->parent_id;
            $categoryModel->save();

            foreach ($languages as $key => $language) {
                $categoryModel->translateOrNew($language->locale)->name             = $request->name[$language->id];
                $categoryModel->translateOrNew($language->locale)->description      = $request->description[$language->id];
                $categoryModel->translateOrNew($language->locale)->slug             = $request->name[$language->id];
                $categoryModel->translateOrNew($language->locale)->meta_title       = $request->meta_title[$language->id];
                $categoryModel->translateOrNew($language->locale)->meta_description = $request->meta_description[$language->id];
                $categoryModel->translateOrNew($language->locale)->meta_data        = $request->meta_content[$language->id];
                $categoryModel->save();
            }
            $this->_updateParent($request->parent_id, $categoryModel->id);

            DB::commit();
            return redirect()->route('categories.index');
        } catch (Exception $e) {
            DB::rollback();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::beginTransaction();
        try {
            $categoryModel = $this->categoryModel->findOrFail($id);
            $checkParent   = $this->categoryModel->where('parent_id', $id)
                                                 ->get()->toArray();
            if (empty($checkParent)) {
                $categoryModel->delete();
                $categoryModel->deleteTranslations();
                DB::commit();
                return response()->json(['status' => true], 200);
            }
            return response()->json(['status' => false], 422);
        } catch (Exception $e) {
            DB::rollback();
        }
    }


    public function _updateParent($parent_id = 0, $id) {
        $categoryModel  = $this->categoryModel->findOrFail($id);
        
        if ($parent_id == 0) {
            $categoryModel->depth = $id;
        } else {
            $categoryParent       = $this->categoryModel->findOrFail($parent_id);
            $categoryModel->depth = $categoryParent->depth."/".$id;
        }
        $categoryModel->save();
    }

    public function _validateInsert($request) {
        $rules = array(
                    'name.*'    => 'between:1,255',
                    'parent_id' => 'required',
                    'status'    => ['required', Rule::in([StatusConfig::CONST_AVAILABLE, StatusConfig::CONST_DISABLE])]
                    );
        $messages = array();
        $attribute = array(
            'name.*'    => trans('backend.category.name'),
            'parent_id' => trans('backend.category.parent'),
            'status'    => trans('backend.status')
        );

        $this->validate($request, $rules, $messages, $attribute);
    }
}

app/Http/Controllers/Backend/DriverController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Libs\Configs\StatusConfig;
use App\Models\Driver;
use App\Models\Group;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;


class DriverController extends Controller
{
    private $driverModel;
    private $groupModel;
    private $userModel;

    public function __construct() {
        $this->driverModel = new Driver();
        $this->userModel = new User();
        $this->groupModel = new Group();
    }

    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function list(Request $request) {

        $drivers = $this->driverModel::with('user', 'group')->paginate(10);
        return response()->json($drivers);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Foundation\Application|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index() {
        return view('Backend.Contents.driver.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Foundation\Application|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function create() {

        $tpl = [];

        $tpl['groups'] = $this->groupModel::get();

        $tpl['categories_car'] = [
            '1' =>'Xe máy',
            '2' => "Ô tô"
        ];


        return view('Backend.Contents.driver.add', $tpl);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request) {
        $request->flash();
        $this->_validateInsert($request);
        DB::beginTransaction();


        try {
            $this->userModel->name     = $request->name;
            $this->userModel->email    = $request->email;
            $this->userModel->phone    = $request->phone;
            $this->userModel->password = Hash::make('123456');
            $this->userModel->status   = StatusConfig::CONST_AVAILABLE;
            $this->userModel->save();

            $this->driverModel->code = $request->code;
            $this->driverModel->address = $request->address;
            $this->driverModel->old = $request->old;
            $this->driverModel->images = $request->images;
            $this->driverModel->category_car = $request->category_car;
            $this->driverModel->card_id = $request->card_id;
            $this->driverModel->licence_id = $request->licence_id;
            $this->driverModel->license_plates = $request->license_plates;
            $this->driverModel->group_id = $request->group_id;

            $this->driverModel->user_id =  $this->userModel->id;
            $this->driverModel->save();

            DB::commit();
            return redirect()->route('drivers.index')->with('actions', 'success');
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Foundation\Application|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit($id) {

        $tpl = [];
        $tpl['driver'] = $this->driverModel->with('user')->findOrFail($id);
        $tpl['groups'] = $this->groupModel::get();
        $tpl['categories_car'] = [
            '1' =>'Xe máy',
            '2' => "Ô tô"
        ];

        return view('Backend.Contents.driver.add', $tpl);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id) {
        $request->flash();
        DB::beginTransaction();
        $driverModel = $this->driverModel->findOrFail($id);
        $userModel = $this->userModel->findOrFail($driverModel->user_id);

        try {
            $userModel->name     = $request->name;
            $userModel->phone    = $request->phone;
            $userModel->save();

            $driverModel->address = $request->address;
            $driverModel->old = $request->old;
            $driverModel->images = $request->images;
            $driverModel->category_car = $request->category_car;
            $driverModel->card_id = $request->card_id;
            $driverModel->licence_id = $request->licence_id;
            $driverModel->license_plates = $request->license_plates;
            $driverModel->group_id = $request->group_id;
            $driverModel->save();
            DB::commit();
            return redirect()->route('drivers.index')->with('actions', 'success');
        } catch (\Exception $e) {
            DB::rollback();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id) {
        DB::beginTransaction();
        try {
            $this->driverModel->find($id)->delete();
            DB::commit();
            return response()->json(['status' => false], 200);
        } catch (\Exception $e) {
            DB::rollback();
        }
    }


    public function _validateInsert($request) {
        $rules = array(
            'name' => 'between:1,255',
            'code' => 'between:1,255',
            'email' => 'required|between:1,255|unique:users,email',
        );
        $messages = array();
        $attribute = array(
            'name' => 'Tên đội không được để trống',
            'code' => 'Mã dội không được để trống',
        );

        $this->validate($request, $rules, $messages, $attribute);
    }
}

resources/views/Backend/Layouts/_angular.blade.php
<!--jQuery [ REQUIRED ]-->
<script src="{{ url('') }}/Nifty/js/jquery.min.js"></script>
<!--BootstrapJS [ RECOMMENDED ]-->
<script src="{{ url('') }}/Nifty/js/bootstrap.min.js"></script>


<!-- lib -->
<script src="{{ url('angularJs/lib') }}/angular.min.js"></script>
<script src="{{ url('angularJs/lib') }}/angular-sanitize.js"></script>
<script src="{{ url('angularJs/lib') }}/angular-ui.min.js"></script>
<script src="{{ url('angularJs/lib') }}/ng-Route.min.js"></script>
<script src="{{ url('angularJs/lib') }}/paging.js"></script>

<script src="{{ url('Backend/js/ngApp.js') }}"></script>

<!-- driectives -->
<script src="{{ url('angularJs/uses/directives') }}/myCkeditor.js"></script>
<script src="{{ url('angularJs/uses/directives') }}/myDatepicker.js"></script>
<script src="{{ url('angularJs/uses/directives') }}/ngdom.js"></script>
<script src="{{ url('angularJs/uses/directives') }}/ngEnter.js"></script>
<script src="{{ url('angularJs/uses/directives') }}/slugText.js"></script>
<script src="{{ url('angularJs/uses/directives') }}/myRenderImage.js"></script>
<script src="{{ url('angularJs/uses/directives') }}/myLFM.js"></script>

<!-- services -->
<script src="{{ url('angularJs/uses/factory') }}/apply.js"></script>
<script src="{{ url('angularJs/uses/factory') }}/myBootbox.js"></script>
<script src="{{ url('angularJs/uses/factory') }}/myLoader.js"></script>
<script src="{{ url('angularJs/uses/factory') }}/myNotify.js"></script>

<script src="{{ url('ckeditor/ckeditor.js') }}"></script>

resources/views/Backend/Layouts/_css.blade.php
<link href="{{ url('Backend/css/backend.css') }}" rel="stylesheet">

resources/views/Backend/Layouts/_css_default.blade.php
<link href="{{ url('Nifty/css/bootstrap.min.css') }}" rel="stylesheet">

<link href="{{ url('Nifty/css/bootstrap.min.css') }}" rel="stylesheet">
<!-- Nifty css -->
<link href="{{ url('Nifty/css/nifty.min.css') }}" rel="stylesheet">
<!-- Nifty demo icon css -->
<link href="{{ url('Nifty/css/demo/nifty-demo-icons.min.css') }}" rel="stylesheet">
<!-- Nifty demo css -->
<link href="{{ url('Nifty/css/demo/nifty-demo.min.css') }}" rel="stylesheet">
<!-- Nifty loader -->
<link href="{{ url('Nifty/plugins/css-loaders/css/css-loaders.css') }}" rel="stylesheet">
<!-- Nifty front awesome -->
<link href="{{ url('Nifty/plugins/font-awesome/css/font-awesome.min.css') }}" rel="stylesheet">
<!-- Nifty datepicker -->
<link href="{{ url('Nifty/plugins/bootstrap-datepicker/bootstrap-datepicker.min.css') }}" rel="stylesheet">
<!-- Nifty timePicker -->
<link href="{{ url('Nifty/plugins/bootstrap-timepicker/bootstrap-timepicker.min.css') }}" rel="stylesheet">
<!-- tag tab -->
<link href="{{ url('Nifty/plugins/bootstrap-tagsinput/bootstrap-tagsinput.min.css') }}" rel="stylesheet">
<!-- selected -->
<link href="{{ url('Nifty/plugins/bootstrap-select/bootstrap-select.min.css') }}" rel="stylesheet">
<!-- Radio switchery -->
<link href="{{ url('Nifty/plugins/switchery/switchery.min.css') }}" rel="stylesheet">

<link href="{{ url('Nifty/plugins/spinkit/css/spinkit.min.css') }}" rel="stylesheet">

<link href="{{ url('Nifty/plugins/themify-icons/themify-icons.min.css') }}" rel="stylesheet">

<link href="{{ url('Nifty/plugins/jquery-toast/jquery-toast-plugin.css') }}" rel="stylesheet">

<link href="{{ url('Nifty') }}/plugins/bootstrap-table/bootstrap-table.min.css" rel="stylesheet">

<link href="{{ url('Nifty') }}/plugins/sweet-alert/sweetalert2.min.css" rel="stylesheet">

<link href="{{ url('Nifty') }}/plugins/dropzone/dropzone.min.css" rel="stylesheet">

<link href="{{ url('Nifty') }}/plugins/select2/css/select2.min.css" rel="stylesheet">

<link href="{{ url('Nifty') }}/plugins/parsley/css/parsley.css" rel="stylesheet">

<link href="{{ url('Nifty') }}/plugins/flag-icon-css/css/flag-icon.min.css" rel="stylesheet">

<link href="{{ url('Nifty') }}/plugins/datatable/datatables.min.css" rel="stylesheet">

resources/views/Backend/Layouts/_footer.blade.php
<footer id="footer">
    <!-- <div class="show-fixed pad-rgt pull-right">
        You have <a href="#" class="text-main"><span class="badge badge-danger">3</span> pending action.</a>
    </div>
    <div class="hide-fixed pull-right pad-rgt">
        14GB of <strong>512GB</strong> Free.
    </div> -->
    <p class="pad-lft">&#0169; 2017 Your Company</p>
 </footer>

resources/views/Backend/Layouts/_js_default.blade.php
<!-- Nifty JS -->
<script src="{{ url('') }}/Nifty/js/nifty.min.js"></script>
<!-- 
<script src="{{ url('') }}/Nifty/js/demo/nifty-demo.min.js"></script> -->

<!-- Nifty select -->
<script src="{{ url('') }}/Nifty/plugins/bootstrap-select/bootstrap-select.min.js"></script>
<!-- Nifty Icon -->
<script src="{{ url('') }}/Nifty/js/demo/icons.js"></script>
<!-- Nifty switchery -->
<script src="{{ url('') }}/Nifty/plugins/switchery/switchery.min.js"></script>
<!-- nifty tag -->
<script src="{{ url('') }}/Nifty/plugins/bootstrap-tagsinput/bootstrap-tagsinput.min.js"></script>
<!-- timepicker -->
<script src="{{ url('') }}/Nifty/plugins/bootstrap-timepicker/bootstrap-timepicker.min.js"></script>
<!-- datepicker -->
<script src="{{ url('') }}/Nifty/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>

<script src="{{ url('') }}/Nifty/plugins/jquery-toast/jquery-toast-plugin.js"></script>

<script src="{{ url('') }}/Nifty/plugins/bootstrap-table/bootstrap-table.min.js"></script>


<script src="{{ url('') }}/Nifty/plugins/sweet-alert/sweetalert2.min.js"></script>

<script src="{{ url('') }}/Nifty/plugins/dropzone/dropzone.min.js"></script>

<script src="{{ url('') }}/Nifty/plugins/select2/js/select2.min.js"></script>

<script src="{{ url('') }}/Nifty/plugins/parsley/js/parsley.min.js"></script>

<script src="{{ url('') }}/Nifty/plugins/datatable/datatables.min.js"></script>

<script src="{{ url('') }}/Nifty/plugins/datatable/datatables.min.js"></script>

<script src="{{ url('') }}/vendor/laravel-filemanager/js/lfm.js"></script>

resources/views/Backend/Layouts/_menu.blade.php
<nav id="mainnav-container">
    <div id="mainnav">
        <div id="mainnav-menu-wrap">
            <div class="nano">
                <div class="nano-content">
                    <div id="mainnav-profile" class="mainnav-profile">
                        <div class="profile-wrap text-center">
                            <div class="pad-btm">
                                <img class="img-circle img-md" src="@if (Auth::check()) {{ url('') }}/{{Auth::user()->avatar}} @endif" alt="Profile Picture">
                            </div>
                            <a href="#profile-nav" class="box-block" data-toggle="collapse" aria-expanded="false">
                                <p class="mnp-name">@if (Auth::check()) {!! Auth::user()->name !!} @endif</p>
                                <span class="mnp-desc">@if (Auth::check()) {!! Auth::user()->email !!} @endif</span>
                            </a>
                        </div>
                    </div>
                    <ul id="mainnav-menu" class="list-group">
                        <li class="list-divider"></li>
                        <li class="list-header">{!! trans('backend.menu.manager')  !!}</li> 

                        <li class="
                                {{ request()->is('admin/categories') 
                                || request()->is('admin/categories/*')
                                ? 'active-sub active': '' }}">
                            <a href="#">
                                <i class="ti-settings"></i>
                                <span class="menu-title">{!! trans('backend.menu.product')  !!}</span>
                                <i class="arrow"></i>
                            </a>                    
                            <ul class="collapse">
                                <li class="{{ request()->is('admin/categories') || request()->is('admin/categories/*') ? 'active-link': '' }}">
                                    <a href="{{ route('categories.index') }}"><i class="ti-angle-double-right">
                                    </i>{!! trans('backend.menu.category')  !!}</a>
                                </li>
                            </ul>
                        </li>

                        <li class="
                                {{ request()->is('admin/groups')
                                || request()->is('admin/groups/*')
                                ? 'active-sub active': '' }}">
                            <a href="#">
                                <i class="ti-settings"></i>
                                <span class="menu-title">Đội xe</span>
                                <i class="arrow"></i>
                            </a>
                            <ul class="collapse">
                                <li class="{{ request()->is('admin/groups') || request()->is('admin/groups/*') ? 'active-link': '' }}">
                                    <a href="{{ route('groups.index') }}">
                                        <i class="ti-angle-double-right"></i>Đội xe
                                    </a>
                                </li>
                            </ul>
                        </li>

                        <li class="
                                {{ request()->is('admin/drivers')
                                || request()->is('admin/drivers/*')
                                ? 'active-sub active': '' }}">
                            <a href="#">
                                <i class="ti-settings"></i>
                                <span class="menu-title">Lái xe</span>
                                <i class="arrow"></i>
                            </a>
                            <ul class="collapse">
                                <li class="{{ request()->is('admin/drivers') || request()->is('admin/drivers/*') ? 'active-link': '' }}">
                                    <a href="{{ route('drivers.index') }}"><i class="ti-angle-double-right">
                                        </i>Lái xe</a>
                                </li>
                            </ul>
                        </li>

                        <li class="
                                {{ request()->is('admin/orders')
                                || request()->is('admin/orders/*')
                                ? 'active-sub active': '' }}">
                            <a href="#">
                                <i class="ti-settings"></i>
                                <span class="menu-title"> Đơn hàng</span>
                                <i class="arrow"></i>
                            </a>
                            <ul class="collapse">
                                <li class="{{ request()->is('admin/orders') || request()->is('admin/orders/*') ? 'active-link': '' }}">
                                    <a href="{{ route('orders.index') }}"><i class="ti-angle-double-right">
                                        </i> Đơn hàng</a>
                                </li>
                            </ul>
                        </li>
                        
                        <li class="
                                {{ request()->is('admin/users') 
                                || request()->is('admin/users/*')
                                || request()->is('admin/roles') 
                                || request()->is('admin/roles/*')
                                ? 'active-sub active': '' }}">
                            <a href="#">
                                <i class="demo-pli-male"></i>
                                <span class="menu-title">{!! trans('backend.menu.users')  !!}</span>
                                <i class="arrow"></i>
                            </a>                    
                            <ul class="collapse">
                                <li class="{{ request()->is('admin/users') || request()->is('admin/users/*') ? 'active-link': '' }}">
                                    <a href="{{ route('users.index') }}"><i class="ti-angle-double-right">
                                    </i>{!! trans('backend.menu.users') !!}</a>
                                </li>
                                <li class="{{ request()->is('admin/roles') || request()->is('admin/roles/*') ? 'active-link': '' }}">
                                    <a href="{{ route('roles.index') }}"><i class="ti-angle-double-right"></i>{!! trans('backend.menu.role')  !!}</a>
                                </li>
                            </ul>
                        </li>
                        <li class="
                                {{ request()->is('admin/languages') 
                                || request()->is('admin/languages/*')
                                ? 'active-sub active': '' }}">
                            <a href="#">
                                <i class="ti-settings"></i>
                                <span class="menu-title">{!! trans('backend.menu.setting')  !!}</span>
                                <i class="arrow"></i>
                            </a>                    
                            <ul class="collapse">
                                <li class="{{ request()->is('admin/languages') || request()->is('admin/languages/*') ? 'active-link': '' }}">
                                    <a href="{{ route('languages.index') }}"><i class="ti-angle-double-right">
                                    </i>{!! trans('backend.menu.language')  !!}</a>
                                </li>
                            </ul>
                        </li>


                    </ul>

                    


                    <div class="mainnav-widget">
                        <div class="show-small">
                            <a href="#" data-toggle="menu-widget" data-target="#demo-wg-server">
                                <i class="demo-pli-monitor-2"></i>
                            </a>
                        </div>
                        <div id="demo-wg-server" class="hide-small mainnav-widget-content">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>