routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Auth', 'middleware' => 'web'], function() {
    Route::get('login',  'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
    Route::get('register', 'LoginController@register')->name('register');
});

Route::group(['prefix' => 'admin/users'], function() {
    Route::get('user-permission/{id}', '\DangKien\RolePer\Controllers\UserRoleController@index')->name('user-permission.index');
    Route::post('user-permission/{id}', '\DangKien\RolePer\Controllers\UserRoleController@store')->name('user-permission.store');
    Route::get('role-permission/{id}', '\DangKien\RolePer\Controllers\RolePermissionController@index')->name('roles-permission.index');
    Route::post('role-permission/{id}', '\DangKien\RolePer\Controllers\RolePermissionController@store')->name('roles-permission.store');
});

Route::resource('admin/roles', '\DangKien\RolePer\Controllers\RoleController');
Route::group(['prefix' => '', 'middleware' => 'role:superadmin'], function() {
    Route::resource('admin/permissions', '\DangKien\RolePer\Controllers\PermissionController');
    Route::resource('admin/permissions-group', '\DangKien\RolePer\Controllers\PermissionGroupController');
});

Route::group(['prefix' => 'admin', 'namespace' => 'Backend'], function() {
    Route::get('/laravel-filemanager', '\UniSharp\LaravelFilemanager\controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\UniSharp\LaravelFilemanager\controllers\UploadController@upload');
    

    Route::get('users/profile', 'UserController@show')->name('users.profile');
    Route::post('users/profile', 'UserController@updateSeft')->name('users.updateProfile');

    Route::get('users/change-password', 'UserController@change')->name('users.change');
    Route::post('users/change-password', 'UserController@changePassword')->name('users.changePassword');

    Route::resource('users', 'UserController');

    Route::resource('groups', 'GroupController');

    Route::resource('drivers', 'DriverController');

    Route::resource('orders', 'OrderController');

    Route::resource('languages', 'LanguagesController', ['except'=>['destroy']]);

    Route::resource('categories', 'CategoryController', ['except'=>['destroy']]);
});

Route::group(['prefix' => 'rest/admin'], function() {
    Route::get('users', 'Backend\UserController@getList');
    Route::delete('users/{id}', 'Backend\UserController@destroy');

    Route::get('languages', 'Backend\LanguagesController@list');
    Route::delete('languages/{id}', 'Backend\LanguagesController@destroy');

    Route::get('categories', 'Backend\CategoryController@list');
    Route::delete('categories/{id}', 'Backend\CategoryController@destroy');

    Route::get('groups', 'Backend\GroupController@list');
    Route::delete('groups/{id}', 'Backend\GroupController@destroy');

    Route::get('drivers', 'Backend\DriverController@list');
    Route::delete('drivers/{id}', 'Backend\DriverController@destroy');

    Route::get('orders', 'Backend\OrderController@list');
    Route::delete('orders/{id}', 'Backend\OrderController@destroy');
});

app/Models/Permission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use DangKien\RolePer\RolePerPermission;

class Permission extends RolePerPermission
{
    protected $table = 'permissions';

    public function permission_group() {
    	return $this->belongsTo('App\Models\PermissionGroup', 'permission_group_id', 'id');
    }
}

resources/views/user_permission/permission/add.blade.php
@extends('Backend.Layouts.default')
@section ('title', 'ZeLike 澤樣室內設計')
@section('content')
	<div id="content-container">
		<div id="page-head">
            <div id="page-title">
                <h1 class="page-header text-overflow">{{ trans('backend.permission.lable') }}</h1>
            </div>
            <ol class="breadcrumb">
			<li><a href="#"><i class="demo-pli-home"></i></a></li>
			<li><a href="#">{{ trans('backend.permission.add') }}</a></li>
            </ol>
        </div>
		<div id="page-content">
		    <div class="panel-body">
		        <div class="panel">
		            <div class="panel">
			            <div class="panel-heading">
			               
			            </div>
			            @if (!isset($permission)) 
							<form action="{{ route('permissions.store') }}" method="POST" enctype="multipart/form-data">
							@method ('POST')
						@else
							<form action="{{ route('permissions.update', $permission->id) }}" method="POST" enctype="multipart/form-data">
								@method ('PUT')
			            @endif

			            	@csrf
			            	
			                <div class="panel-body col-sm-offset-2">
			                    <div class="row">
			                        <div class="col-sm-10">
			                            <div class="form-group">
			                                <label class="control-label">{{ trans('backend.permission.name') }}</label>
			                                <input type="text" name="name" class="form-control" 
			                                value="{{ old('name') ? old('name') :  @$permission->name }}">
			                                @if ($errors->has('name'))
				                            	<p class="text-left text-danger">{{ $errors->first('name') }}</p>
				                            @endif
			                            </div>
			                        </div> 
			                        <div class="col-sm-10">
			                            <div class="form-group">
			                                <label class="control-label">{{ trans('backend.permission.display_name') }}</label>
			                                <input type="text" name="display_name" class="form-control" value="{{ old('display_name') ? old('display_name') : @$permission->display_name }}">
			                                @if ($errors->has('display_name'))
				                            	<p class="text-left text-danger">{{ $errors->first('display_name') }}</p>
				                            @endif
			                            </div>
			                        </div>

			                        <div class="col-sm-10">
			                            <div class="form-group">
			                                <label class="control-label">{{ trans('backend.permission.description') }}</label>
			                                <input type="text" name="description" class="form-control" value="{{ old('description') ? old('description') : @$permission->description }}">
			                                @if ($errors->has('description'))
				                            	<p class="text-left text-danger">{{ $errors->first('description') }}</p>
				                            @endif
			                            </div>
			                        </div>
									@php 
										$per_gr = \App\Models\PermissionGroup::all();
									@endphp
                                    <div class="col-sm-10">
                                        <div class="form-group">
                                            <p>{{ trans('backend.permission.group_permission') }}</p>
                                            <select id="demo-select2" name="per_gr" class=" demo-select2 selected-2" style="width: 100%;">
                                            	@foreach ($per_gr as $key => $gr) 
													<option 
														@if(  $gr->id == old('per_gr') || $gr->id == @$permission->permission_group->id) 
															{{"selected"}}
														@endif
														value="{{ $gr->id }}"
													> {!! $gr->display_name !!}</option>}
                                            	@endforeach
                                            </select>
                                        </div>
                                    </div>
			                    </div>
			                    <div class="row">
			                    	<div class="col-sm-10">
			                        	<button type="submit" class="btn btn-primary btn-block">{{ trans('backend.actions.submit') }}</button>
			                        </div>
			                    </div>
			                </div>
			                
					   	</form>
			        </div>
		        </div>
		    </div>
		</div>
	</div>
@endsection

@section ('myJs')
	<script>
		$(document).ready(function() {
		    $('.selected-2').select2();
		});
	</script>
@endsection

@section ('myCss')
	
@endsection

resources/views/user_permission/permission/index.blade.php
@extends('Backend.Layouts.default')
@section ('title', 'ZeLike 澤樣室內設計')
@section('content')
	<div id="content-container">
		<div id="page-head">
            <div id="page-title">
                <h1 class="page-header text-overflow">{{ trans('backend.permission.lable') }}</h1>
            </div>
            <ol class="breadcrumb">
				<li><a href="#"><i class="demo-pli-home"></i></a></li>
				<li><a href="#">List</a></li>
            </ol>
        </div>
		<div id="page-content">
		    <div class="panel-body">
		        <div class="panel">
		            <div class="panel-heading">
		                
		            </div>
		            <div class="panel-body">
		            	<div class="pad-btm form-inline">
				            <div class="row">
				                <div class="col-sm-6 table-toolbar-left">
				                   <a href="{{ route('permissions.create') }}" id="demo-btn-addrow" class="btn btn-purple"><i class="demo-pli-add"></i> {{ trans('backend.permission.add') }}</a>
				                </div>
				                <div class="col-sm-6 table-toolbar-right">
				                    <div class="form-group col-sm-12">
				                        <input id="demo-input-search2" type="text" placeholder="Tìm kiếm" class="form-control col-sm-
				                        8" autocomplete="off">
				                    </div>
				                </div>
				            </div>
				        </div>
		                <div class="table-responsive">
		                	@php
		                		$permissions = App\Models\Permission::with('permission_group')->paginate(30);
		                	@endphp
		                    <table class="table table-bordered table-striped">
		                        <thead>
		                            <tr>
		                                <th class="text-center">#</th>
		                                <th>{{ trans('backend.permission.permission') }}</th>
		                                <th>{{ trans('backend.permission.display_name') }}</th>
		                                <th>{{ trans('backend.permission.permission_group') }} </th>
		                                <th>{{ trans('backend.permission.description') }}</th>
		                                <th>{{ trans('backend.actions.action') }}</th>
		                            </tr>
		                        </thead>
		                        <tbody>
	                            	@foreach ($permissions as $key => $permission) 
	                            	<tr>
		                                <td class="text-center"> {{ $key + 1 }} </td>
		                                <td>{{ $permission->name }}</td>
		                                <td>{{ $permission->display_name }}</td>
		                                <td>{{ $permission->permission_group->display_name }}</td>
		                                <td>{{ $permission->description }}</td>
		                                <td class="text-center" style="width: 100px;">
			                                <form action="{{ route('permissions.destroy', $permission->id) }}" method="POST">
			                                	<a class="btn btn-sm btn-info btn-icon" href="{{ route('permissions.edit', $permission->id) }}">
			                                		<i class="fa fa-edit icon-lg"></i>
			                                	</a>
			                                    @csrf
			                                    @method('DELETE')
			                                    <button type="submit" class="btn btn-sm btn-danger"><i class="fa fa-trash icon-lg"></i></button>
			                                </form>
			                            </td>
		                            </tr>
		                            @endforeach
		                        </tbody>
		                    </table>
		                    	{{ $permissions->links() }}
		                </div>
		            </div>
		        </div>
		    </div>
		</div>
	</div>
@endsection

@section ('myJs')
@endsection

@section ('myCss')
	
@endsection